languageCode:           "en"
title:                  "FloScss"
baseURL:                "https://floscss.elliott.works"
enableInlineShortcodes: true

pygmentsUseClasses:     true
# you can use ```lang if you want too
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/4.3/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/4.3/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Based on the most popular HTML, CSS, and JS library in the world."
  authors:              "FloSports Product Team"
  social_image_path:    /docs/4.3/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.3/assets/brand/bootstrap-social-logo.png

  current_version:      "0.0.1"
  current_ruby_version: "4.3.1"
  rfs_version:          "9.0.2"
  docs_version:         "4.3"
  repo:                 "https://github.com/flocasts/flo-scss"
  twitter:              "flosports"
  slack:                "https://flosports.slack.com"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.floscss.elliott.works/"
  expo:                 "https://expo.floscss.elliott.works/"
  themes:               "https://themes.floscss.elliott.works/"
  icons:                "https://icons.floscss.elliott.works/"

  download:
    source:             "https://github.com/flocasts/flo-scss/archive/v4.3.1.zip"
    dist:               "https://github.com/flocasts/flo-scss/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    css_hash:         "sha384-XLKOjDgI/sG7klUPkSIfPSKfA1KqPabkrV5LIxcihYUrF6y3RsB0+SlynUUHhr1x"
    js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    js_hash:          "sha384-8d7KL/Wa3ZNXYF6mYRfVEOnf+b+C36kTkEyfN8L2/PvsAyBj/OVmQtoSVdpNec/0"
    js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-LMlJj8rvQfN+wxaPOyXKfaACzQ7GwptBkDvETkjkYfKfLZmv6j3uAgjCJceqAikJ"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    popper_hash:      "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
